### ISSUE TITLE
Activity monitor on mac

### ISSUE THREAD

**Issue by knupel** [processing/processing-experimental#46] opened 2014-02-11 09:01 UTC
Activity monitor about PDEX on mac for information

With PDEX  with freezing
![with pdex with freezing](https://f.cloud.github.com/assets/3332269/2135235/e0fa168c-92fa-11e3-89d9-3bd0596aea46.png)
with pdex without freezing
![with pdex without freezing](https://f.cloud.github.com/assets/3332269/2135236/e100f682-92fa-11e3-9c12-a8b98ea8ed85.png)
without pdex
![without pdex](https://f.cloud.github.com/assets/3332269/2135237/e102949c-92fa-11e3-840d-ade7b05e03d5.png)

**Comment by Manindra29** [comment] 2014-04-22 09:06
Duplicate of #27

**Closed as completed by Manindra29** 2014-04-22 09:06 UTC
