### ISSUE TITLE
Freeze

### ISSUE THREAD

**Issue by knupel** [processing/processing-experimental#27] opened 2013-10-11 12:08 UTC
I don't know if it's same problem source than "PermGem"
But sometime after Processing Freeze if try to launch a sketch and miss a void or I try to change something in code, not at the beggining but after two or three hours of coding or after maybe the computer is on Standby. Processing restart after one minute...
I must quit Processing and restart the computer

The message is :

Exception in thread "AWT-EventQueue-0" java.lang.StackOverflowError
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at sun.misc.Launcher$ExtClassLoader.findClass(Launcher.java:229)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:295)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:295)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:249)
    at processing.mode.experimental.ASTGenerator.loadClass(ASTGenerator.java:1233)
    at processing.mode.experimental.ASTGenerator.findClassIfExists(ASTGenerator.java:1164)
    at processing.mode.experimental.ASTGenerator.resolveExpression3rdParty(ASTGenerator.java:552)
    at processing.mode.experimental.ASTGenerator.resolveExpression3rdParty(ASTGenerator.java:707)
    at processing.mode.experimental.ASTGenerator.resolveExpression3rdParty(ASTGenerator.java:707)
    at processing.mode.experimental.ASTGenerator.resolveExpression3rdParty(ASTGenerator.java:707)
    at processing.mode.experimental.ASTGenerator.resolveExpression3rdParty(ASTGenerator.java:707)
    at processing.mode.experimental.ASTGenerator.resolveExpression3rdParty(ASTGenerator.java:707)
    at processing.mode.experimental.ASTGenerator.resolveExpression3rdParty(ASTGenerator.java:707)
    at processing.mode.experimental.ASTGenerator.resolveExpression3rdParty(ASTGenerator.java:707)

**Comment by Manindra29** [comment] 2013-10-11 19:51
I'm afraid the description is not very clear.

> But sometime after Processing Freeze if try to launch a sketch

Do you mean  P5 freezes after opening a sketch or after running a sketch? Or are you trying to open a sketch after P5 is frozen?

> Processing restart after one minute

I guess you mean you're restarting it yourself? 

In case Processing freezes, you can just end the process(http://osxdaily.com/2012/03/02/force-quit-mac-apps/) rather than restarting your system..

Moreover, this seems like a different bug, unrelated to the Permgen one. How many times have you encountered this bug?

**Comment by knupel** [comment] 2013-10-14 07:39
Sorry for my confusing description.
P5 freeze (75% of time) after I try to run a sketch, the sketch is a complex one, this one I give you a link in the previous post. If you need the other sketches, say me. 
But this type of freezing is not at the begining of coding session but may be after three or four hours.
I need to restart the computer to resolve this freezing. So if I understand your link quit the process is better than force to quit and less hard to restart the system ? it's an intermediary solution ?

I hope is clearer.

**Comment by Manindra29** [comment] 2013-10-22 06:18
PDE X has been updated to v1.0.2b. Try it out and let me know if you're still observing this behaviour. Thanks for helping out with the bugs. 

And yes, force quitting the process is better/faster than restarting your system.

**Comment by knupel** [comment] 2013-10-22 07:46
OK, that's download, I test ASAP. and give the feedback in return.

**Comment by knupel** [comment] 2013-10-22 21:17
Sometime defitively freeze with no error message, with four sketches open. And after that Processing freeze more and more often...like five minutes open and freeze. I try "force to quit" and quit processing by the monitor activity same resulte freeze very quick after !

**Comment by Manindra29** [comment] 2014-06-10 09:27
Since this issue doesn't clearly state a way to reproduce the problem, I'm closing it.

I'm aware of the memory usage issue and will be investigating it further.

**Closed as completed by Manindra29** 2014-06-10 09:27 UTC
Labels: bug
