### ISSUE TITLE
Persistent window

### ISSUE THREAD

**Issue by knupel** [processing/processing-experimental#32] opened 2013-10-22 21:28 UTC
Persistent popup suggestion is back !
![capture decran 2013-10-22 a 23 28 04](https://f.cloud.github.com/assets/3332269/1385597/ded74d76-3b60-11e3-8e8c-cd796df9adaf.png)

**Comment by Manindra29** [comment] 2013-10-24 08:08
Not observing this on Windows or Linux. So looks like its OS X specific.

**Comment by knupel** [comment] 2013-10-24 12:05
Yep, I'm on OSX 10.7.5
Is not all the time but sometime the window be persistente. I don't find what is the origin of that, because gloabally is work fine ( 95% of time)  ! .

**Comment by Manindra29** [comment] 2013-12-03 21:01
When does this behaviour happen? While switching between windows? What keyboard combo do you use to switch between windows? I use a OS X Mountain Lion VM on VirtualBox for Mac testing. I couldn't manage to reproduce this error..

**Comment by knupel** [comment] 2013-12-04 08:46
that's happen when I use "show outline" by menu or by the keyboard shortcut, same behavior with P203 and P210, my machine is an iMac 2012, with OS 10.7.5
![capture decran 2013-12-04 a 09 45 40](https://f.cloud.github.com/assets/3332269/1671654/8424664e-5cc0-11e3-8c8b-eef6059e4a4c.png)

**Comment by Manindra29** [comment] 2013-12-04 10:36
**Which popup** are you referring to in this issue - the completion suggestion popup or sketch outline popup? Initial bug report mentioned the suggestion popup and now you are referring to sketch outline popup.
Sketch outline popup is designed to persist until you hit escape key or click away from it.

**Comment by knupel** [comment] 2013-12-04 11:14
Sorry, I mix two issues, i'm tirred !
For the persistent windows that's happen often with P203. generally when I write fast and don't use the the suggesting window. But it's hard to explain what's and when is happen exactly. I try to understand more what's happen and explain to you later.

**Comment by Manindra29** [comment] 2013-12-04 14:22
Sure, no problem. Exact steps to reproduce the problem will be really helpful in tracking and fixing the issue.

**Comment by MichaelPaulukonis** [comment] 2014-02-27 02:44
I have also seen this behavior on Windows 7 64 bit.
I will try to get steps to reproduce.

**Comment by Manindra29** [comment] 2014-04-22 09:09
After a lot of testing on OS X 10.9, Windows 7 and Ubuntu 12.10, I've not been able to reproduce this issue. I had implemented some fixed for it already. So closing the issue for now. If you still observe this odd behaviour, please create a new issue with steps to reproduce the problem.

**Closed as completed by Manindra29** 2014-04-22 09:09 UTC
Labels: bug
