### ISSUE TITLE
When autocompleting function, column is sometimes off by 1

### ISSUE THREAD

**Issue by tobbi** [processing/processing-experimental#38] opened 2013-12-29 18:07 UTC
See this screencast:
https://www.dropbox.com/sc/gjj2pnrhmp3d1m2/uRFKN943jC

**Comment by tobbi** [comment] 2013-12-29 18:09
Processing version 2.1, PDEX version 1.0.2b

**Comment by Manindra29** [comment] 2014-01-11 14:37
Can you share a small sketch with which this bug can be reproduced? This looks like an isolated bug. Haven't been able to reproduce it.

**Comment by Manindra29** [comment] 2014-01-22 19:02
@tobbi, please let me know how you produced this bug so that I can track and fix it. This could be an important edge case which I missed.

**Comment by tobbi** [comment] 2014-01-22 19:13
Hello, sorry for the delayed response on this. I uploaded my college sketch here: https://www.dropbox.com/s/98im01wj1iso3ru/testcase.zip (it contains more than needed). Anyway, STR:

After opening it with Processing 2.1, go to line 36, right after the comment, press Enter. Now type 'setC' and let it autocomplete. Select "setCurrentMagnifier" and press Enter. As you can see in the following screencast it works sometimes and sometimes it does not. See http://screencast.com/t/9xzy3uLN5wda

Name of the sketch main file: sintomark

**Comment by Manindra29** [comment] 2014-01-22 19:31
I tried for 10 minutes continuously to reproduce the bug on Windows 7, but couldn't. I also notice that the suggestion window is stuck in your screen-cast. This increasingly leads me to believe this bug may have something do with OS X specifically(Processing 2.1 uses JDK 7 on OS X, which has been known to have odd quirks). I'll investigate further on OS X. 

Thanks for reporting!

**Comment by tobbi** [comment] 2014-01-24 13:25
Have you had any luck reproducing the issue on OS X?

**Comment by Manindra29** [comment] 2014-01-29 17:28
Yes, I was able to reproduce the issue. I think I also understand why it doesn't happen always. There's a race condition happening here between two threads, so it's difficult to reproduce accurately. Will work on a fix.

**Comment by Manindra29** [comment] 2014-03-20 15:19
Alright, so after some testing, I've not been able to reproduce this bug. So hopefully it's been fixed; closing  the issue for now.

**Closed as completed by Manindra29** 2014-03-20 15:19 UTC
Labels: bug, critical
