### ISSUE TITLE
Live-error checker is inefficient with memory.

### ISSUE THREAD

**Issue by aengelke** [processing/processing-experimental#1] opened 2013-06-29 12:32 UTC
See processing/processing#1861, processing/processing#1764.

OS: Windows 7 32bit, 3GB RAM
1. Open a blank PDE and switch to the experimental mode.
2. Look at the task manager: Processing --> 90MB of the memory
3. Open a sketch: Processing --> 120MB of the memory
4. Close the blank sketch: Processing --> still 120MB of the memory
5. Redo Steps 3 and 4 about 10 times: At about 200MB of memory, PDE won't open another sketch. `OutOfMemoryError: PermGen space`

---

After restarting my system and on a fresh restart, I could open 11 sketches and closing them again (so I only have one sketch open!). After trying opening another sktech, Processing says in the output window:

Part 1:
![image](https://f.cloud.github.com/assets/4236689/579897/f9814018-c87a-11e2-8c26-39d81be379a5.png)

Part 2:
![image](https://f.cloud.github.com/assets/4236689/579902/0c9d5740-c87b-11e2-9f19-9480b6b8b24b.png)

And it repeats printing the last lines. (Exception: One time it says `Thread-11` insteaf of the AWT-EventQueue) The cause I am making screenshots is that Processing isn't able to copy the text, because there is not enough memory. I also can't save, edit or copy the sketch. I can't open menus. After about 100 lines of OutOfMemoryErrors, Processing doesn't react anymore.

Processing has to be closed via task manager, because it doesn't react.

**Comment by knupel** [comment] 2013-10-09 07:25
But it's a real problem, isn't it ? For example for me I must work generally with minimuym three sketches open in same time...And I like PDE-X. There is a project to resolve this problem of PermGem Space or it's not possible ?

**Comment by benfry** [comment] 2013-10-09 14:23
@Manindra29 It's possible that you're dealing with a new ClassLoader for each X Mode window, causing it to reload all those Eclipse JAR files (which can't be fast either). There might be a way around this... whether we need to do a design change in the PDE so that it's only creating single Mode instances, or that you might be able to do something in the X Mode code for how things are pulled from the CL.

**Comment by Manindra29** [comment] 2013-10-09 15:07
For each instance of the Editor, a new ClassLoader is needed because: 

Every sketch uses its own set of P5 libraries. Sketches are checked for errors and other stuff by a CompilationChecker instance which uses Eclipse JDT libraries. The last time I'd tried, I was not able to manually specify the classpath of these P5 libraries along with the sketch path - a limitation of JDT since it's not running in a full fledged OSGi environment. There are API methods for it, but I couldn't get them to work.. 

The workaround I devised was to have a separate CompilationChecker instance for every open sketch(window) and add the library paths of the particular sketch(including 'code' folder imports) to the ClassLoader loading the CompilationChecker instance. So for different sketches, each ClassLoader would load the only the appropriate libraries. But I suspect that when a window is closed, the resources aren't getting freed up for some reason, even after I've manually tried to free those classes. On closing a window, RAM usage doesn't go down with PDE X Mode.

The other alternative could be to add paths of all installed libraries to the classpath of a master ClassLoader and use a single CompilationChecker instance. But I think this could affect the efficiency of code completion and other features. Plus, how would this solve the sketch specific 'code' folder imports?

I'm open to ideas.

**Comment by benfry** [comment] 2013-10-09 18:02
Ah, I see... The libraries are not necessarily just the Eclipse RCP/OSGI stuff, but all the libraries that are part of the sketch so that autocomplete, etc work. 

The Eclipse stuff may not be unloading since things are being added to a faux OSGI registry or something like that. Or there's just a simpler memory leak somewhere.

Guess you'd have to futz around with VisualVM or something else to profile the code and figure out what's hanging around.

**Comment by Manindra29** [comment] 2013-10-11 19:58
> Guess you'd have to futz around with VisualVM

I did just that. From the heap dump, it seems just the CompilationChecker isn't getting unloaded after closing its parent Editor window. I've yet to locate the source of the bug though..

**Comment by Manindra29** [comment] 2013-10-11 21:04
@benfry I think I've found a possible solution. The Profiler was showing that heap space wasn't getting reclaimed after a Editor window is closed. I manually set the CompilationChecker's classloader as null and added a `System.gc()` at the end of exiting a Editor instance. Now heap space gets reclaimed correctly on closing of Editor window. Wasn't expecting garbage collection needed to be done manually.. 

Previously, PDE X froze after opening about 7-8 sketches(irrespective of whether they stay open or closed), and one had to force quit. By making the above change, it's now possible to keep opening multiple sketches as long as one stays below the limit of 7-8 open sketches at a time. Will test it out a bit more..

The max window limitation can be overcome by increasing the default 64 MB heap space allotted to Processing by adding the following JVM options to the PDE launch command.

`-Xmx1024m -XX:MaxPermSize=256m`

**Comment by benfry** [comment] 2013-10-20 12:53
I'm nervous about setting the minimum memory to 1 GB across the board—even if it's not used, it can cause launching to fail on machines that have less memory (netbooks, etc). 

I think 7-8 sketches open at once should be fine. Are you doing anything to catch the OutOfMemoryError if that's exceeded? Letting people know what's going on would go a long way here (and would give us the opportunity to tell them how to manually increase the memory setting if they want to have a large number of sketches open).

**Comment by knupel** [comment] 2013-10-20 20:37
For information, In my case, I use 4 sketches in same time in my work session, I open few other sketches and close after I take what I need in this one. Processing freeze after few opening sketches may be trhee or four. For me the problem is not open 7-8 sketches in same time but the PermGem problem come after the 7-8th opening.
My memory alowed to Processing are 10G.

**Comment by Manindra29** [comment] 2013-10-21 07:08
> I'm nervous about setting the minimum memory to 1 GB across the board—even if it's not used, it can cause launching to fail on machines that have less memory (netbooks, etc).

That's definitely not something we would want. I'm catching the Exception generated eventually and pausing the error checking, but it still freezes the PDE. I'll look into catching the Error at the source, directly.

>  would give us the opportunity to tell them how to manually increase the memory setting if they want to have a large number of sketches open

Agreed. People often get confused that the memory setting in the preference is for the entire PDE.

@StanLepunK The memory you've allocated in Preferences is the one allocated to Processing sketches, not the editor itself.

Edit - Updated the bug title.

**Comment by Manindra29** [comment] 2014-07-11 21:05
Fixed with https://github.com/processing/processing/commit/4e5f7c61adf0ee390544665d8937ae8682db6a0a :smile:

**Closed as completed by Manindra29** 2014-07-11 21:05 UTC
Labels: bug, critical
