### ISSUE TITLE
Auto completion sometimes generates wrong code

### ISSUE THREAD

**Issue by fjenett** [processing/processing-experimental#59] opened 2014-04-25 06:36 UTC
Sometimes if i enter a variable name for example and then select that name from the auto completion it inserts the name after the first char of what i entered leading to a wrong name.

Type `spa` in example Array2D
![screen shot 2014-04-25 at 8 32 33 am](https://cloud.githubusercontent.com/assets/59608/2797957/c24c4bf6-cc43-11e3-9387-1e46a9503b7e.png)

Select variable suggested by autocompletion
![screen shot 2014-04-25 at 8 33 19 am](https://cloud.githubusercontent.com/assets/59608/2797959/c92305e6-cc43-11e3-9a03-bcb58e4d1462.png)

Result
![screen shot 2014-04-25 at 8 33 28 am](https://cloud.githubusercontent.com/assets/59608/2797961/cd09db6c-cc43-11e3-950a-5d088000b422.png)

**Comment by Manindra29** [comment] 2014-04-25 20:08
Can you please attach the sketch with which you can reproduce the bug? This is probably a race condition happening..

**Comment by fjenett** [comment] 2014-04-26 03:59
It's "Array2D" from the Processing examples as it says above the first image. :)

**Comment by Manindra29** [comment] 2014-06-10 09:42
I can't reproduce the problem on my Ubuntu machine. I'd made some changes to counter such race conditions. Let me know if you still get this error in the next PDE X release.

**Comment by aengelke** [comment] 2014-06-10 10:31
This seems to be fixed, it doesn't happen on Windows (built from master) anymore.

**Comment by aengelke** [comment] 2014-08-02 15:45
Just came across this: Type `fi`, press space and open CC. Then press enter. It produces: `ffill(,)`.

**Comment by Manindra29** [comment] 2014-08-07 05:23
Closing this here. Now reported in https://github.com/processing/processing/issues/2753

**Closed as completed by Manindra29** 2014-08-07 05:23 UTC
Labels: bug
